{% set version = "1.1.1" %}

package:
  name: pyke
  version: {{ version }}

source:
  url: http://download.sourceforge.net/pyke/pyke3-{{ version }}.zip
  sha256: b877b390e70a2eacc01d97c3a992fde947276afc2798ca3ac6c6f74c796cb6dc

build:
  number: 1004
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3

test:
  imports:
    - pyke

about:
  home: http://sourceforge.net/projects/pyke
  license: MIT
  license_file: LICENSE
  summary: Python Knowledge Engine and Automatic Python Program Generator

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
