{% set version = "1.1.1" %}

package:
  name: pyke
  version: {{ version }}

source:
  url: http://download.sourceforge.net/pyke/pyke3-{{ version }}.zip
  sha256: b877b390e70a2eacc01d97c3a992fde947276afc2798ca3ac6c6f74c796cb6dc

build:
  number: 1005
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyke

about:
  home: http://sourceforge.net/projects/pyke
  license: MIT
  license_file: LICENSE
  summary: Python Knowledge Engine and Automatic Python Program Generator

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
