travis:
  secure:
    BINSTAR_TOKEN: DaJWNk0+AtdQQC5BwT/7OXnRUUKdyrvcbEbJsHqAirxLopwiTlmFiXdF/hWUT7YnYC+GIN7MQNRRUSFORHBO+WtuxraYjdKlxPs7CaEC1K+UAdudmyHw4t1eIMJ2RI34TjOGplZiEgZA2WwYrPIPKxVuAltgHfM+QrxNHJq2s8v3XlNeubqeS8aIVnrt4CY1Dy9fRmIed9ZlAmKaIoRaLvNG2equ9/pleKZJGia1bm+1aIRUVgmLhTzOo2YYxM/IlCd5tCSqklQVvaN/mjYSiuepZPAObsQLBdzRvnK9cmmgq9yeye0r1M6wYLCDbFcd/npyWbo3QljEbzx+GcxvKCa4uWIe6VyZuX3M2ftnHELw2PHGVy1/Vot/RDTooNMPsbn5V+OMuzuWMk8QYdRdzyoacJPnnsT4ZUKb+K2wCxCwqjGZMqRbsIt5aDVckfR80NsEpySIfaxIFHYMVWbPS10p7lGNcfpqocdUuEE8YBvem13duh8+o77m3H+mRyd4AuDb++QRCxsTLevta1bGlksfIAOPjlJfseEBxExRqKx5kEuTaqQ1+PlEeaQqkIt+g8fagGxxLwGfKUtekrky342wNipjBFE4qm90i3XfzSHVzBA2NjKrKp1BTHD05GfglRGeS9a7WMgNaWj3ykZjfvJZ324/rQE1R90dYuaw0OM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
